### ISSUE TITLE
fade in/out request

### ISSUE THREAD

**Issue by rogomantik** [AlbertMontserrat/AMGSoundManager#1]
Could you  implement a mechanism of fade in/out
when play / pause / stop / resume
something like this
https://github.com/pralancer/BackgroundAudioPlayer
I tried to do it myself but I did not succeed

thanks

**Comment by AlbertMontserrat** [comment]
Done ;)
Pod version 1.2

**Comment by AlbertMontserrat** [comment]
84940b08a76118a3d862ae095cbcac38d40cee5a
